version: '3.7'
services:
  postgres:
    image: postgres:latest
    container_name: seed_website_postgres
    restart: always
    ports:
      - 5444:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: seed_website_redis
    restart: always
    ports:
      - 6555:6379
    volumes:
      - redis:/var/lib/redis/data

volumes:
  postgres:
    name: seed-website-db
  redis:
    name: seed-website-redis
